# Generated by Django 6.0.7 on 2026-07-30 12:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_image_url'),
        ('shopping_list', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppinglistitem',
            unique_together={('user', 'ingredient', 'is_purchased')},
        ),
    ]
